<?php

use Illuminate\Database\Seeder;
use App\User;
class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
     public function run()
    {
        $User=[[
            'id'=>'1',
            'id_dependencia'=>'2',
            'id_perfil'=>'1',
            'id_pais'=>'1',
            'id_state'=>'1',
            'id_municipio'=>'1',
            'id_ciudad'=>'1',
            'name'=>'Administrador',
            'email'=>'admin@tensoft.com',
            'avatar'=>'admin.png',
            'password'=>bcrypt('20TenSoft18'),
            'cedula'=>'1',
            'nombres'=>'Administrador',
            'apellidos'=>'SDG',
            'telefono'=>'0000000',
            'sexo'=>'Masculino',
            'ocupacion'=>'Administrador',
            'direccion'=>'Universidad de Oriente',
            'created_at'=>'2017-05-21 10:48:05',
            'updated_at'=>'2017-05-21 10:48:05',
        ],[
            'id'=>'2',
            'id_dependencia'=>'2',
            'id_perfil'=>'7',
            'id_pais'=>'1',
            'id_state'=>'1',
            'id_municipio'=>'1',
            'id_ciudad'=>'1',
            'name'=>'Miguel A. Pagliarulo  T.',
            'email'=>'pagliarulot@edu.com.ve',
            'avatar'=>'1871179320.jpg',
            'password'=>bcrypt('123456'),
            'cedula'=>'1',
            'nombres'=>'Miguel A.',
            'apellidos'=>'Pagliarulo T.',
            'telefono'=>'0000000',
            'sexo'=>'Masculino',
            'ocupacion'=>'Docente',
            'direccion'=>'Universidad de Oriente',
            'created_at'=>'2017-05-21 10:48:05',
            'updated_at'=>'2017-05-21 10:48:05',
        ],[
            'id'=>'3',
            'id_dependencia'=>'2',
            'id_perfil'=>'2',
            'id_pais'=>'1',
            'id_state'=>'1',
            'id_municipio'=>'1',
            'id_ciudad'=>'1',
            'name'=>'Carmelys',
            'email'=>'carmelys@edu.com.ve',
            'avatar'=>'1808051620.jpg',
            'password'=>bcrypt('123456'),
            'cedula'=>'1',
            'nombres'=>'Carmelys',
            'apellidos'=>'Rodriguez',
            'telefono'=>'0000',
            'sexo'=>'Femenino',
            'ocupacion'=>'Docente',
            'direccion'=>'Universidad de Oriente',
            'created_at'=>'2017-05-21 10:48:05',
            'updated_at'=>'2017-05-21 10:48:05',
        ],[
            'id'=>'4',
            'id_dependencia'=>'2',
            'id_perfil'=>'3',
            'id_pais'=>'1',
            'id_state'=>'1',
            'id_municipio'=>'1',
            'id_ciudad'=>'1',
            'name'=>'Yulennys',
            'email'=>'yuleinnys@edu.com.ve',
            'avatar'=>'1147914263.jpg',
            'password'=>bcrypt('123456'),
            'cedula'=>'1',
            'nombres'=>'YULEINNYS M.',
            'apellidos'=>'MARQUEZ B.',
            'telefono'=>'0000000',
            'sexo'=>'Femenino',
            'ocupacion'=>'Administrador',
            'direccion'=>'Universidad de Oriente',
            'created_at'=>'2017-05-21 10:48:05',
            'updated_at'=>'2017-05-21 10:48:05',
        ],[
            'id'=>'5',
            'id_dependencia'=>'2',
            'id_perfil'=>'5',
            'id_pais'=>'1',
            'id_state'=>'1',
            'id_municipio'=>'1',
            'id_ciudad'=>'1',
            'name'=>'Edwin',
            'email'=>'edwinmontilla@edu.com.ve',
            'avatar'=>'1147941394.jpg',
            'password'=>bcrypt('123456'),
            'cedula'=>'1',
            'nombres'=>'Edwin Stiven',
            'apellidos'=>'Montilla Sanchez',
            'telefono'=>'0000000',
            'sexo'=>'Masculino',
            'ocupacion'=>'Estudiante',
            'direccion'=>'Universidad de Oriente',
            'created_at'=>'2017-05-21 10:48:05',
            'updated_at'=>'2017-05-21 10:48:05',
        ],[
            'id'=>'6',
            'id_dependencia'=>'2',
            'id_perfil'=>'5',
            'id_pais'=>'1',
            'id_state'=>'1',
            'id_municipio'=>'1',
            'id_ciudad'=>'1',
            'name'=>'yenny',
            'email'=>'yennymaza@edu.com.ve',
            'avatar'=>'1116417113.jpg',
            'password'=>bcrypt('123456'),
            'cedula'=>'1',
            'nombres'=>'Yenny',
            'apellidos'=>'Maza',
            'telefono'=>'0000000',
            'sexo'=>'Masculino',
            'ocupacion'=>'Estudiante',
            'direccion'=>'Universidad de Oriente',
            'created_at'=>'2017-05-21 10:48:05',
            'updated_at'=>'2017-05-21 10:48:05',
        ],[
            'id'=>'7',
            'id_dependencia'=>'2',
            'id_perfil'=>'5',
            'id_pais'=>'1',
            'id_state'=>'1',
            'id_municipio'=>'1',
            'id_ciudad'=>'1',
            'name'=>'tony',
            'email'=>'claudiorondon@edu.com.ve',
            'avatar'=>'1871181507.jpg',
            'password'=>bcrypt('123456'),
            'cedula'=>'1',
            'nombres'=>'Claudio',
            'apellidos'=>'Rondon',
            'telefono'=>'0000000',
            'sexo'=>'Masculino',
            'ocupacion'=>'Estudiante',
            'direccion'=>'Universidad de Oriente',
            'created_at'=>'2017-05-21 10:48:05',
            'updated_at'=>'2017-05-21 10:48:05',
        ],[
            'id'=>'8',
            'id_dependencia'=>'2',
            'id_perfil'=>'5',
            'id_pais'=>'1',
            'id_state'=>'1',
            'id_municipio'=>'1',
            'id_ciudad'=>'1',
            'name'=>'tonfy',
            'email'=>'tonyfigueras@edu.com.ve',
            'avatar'=>'1871182746.jpg',
            'password'=>bcrypt('123456'),
            'cedula'=>'1',
            'nombres'=>'Tony',
            'apellidos'=>'Figueras',
            'telefono'=>'0000000',
            'sexo'=>'Masculino',
            'ocupacion'=>'Estudiante',
            'direccion'=>'Universidad de Oriente',
            'created_at'=>'2017-05-21 10:48:05',
            'updated_at'=>'2017-05-21 10:48:05',
        ],[
            'id'=>'9',
            'id_dependencia'=>'2',
            'id_perfil'=>'5',
            'id_pais'=>'1',
            'id_state'=>'1',
            'id_municipio'=>'1',
            'id_ciudad'=>'1',
            'name'=>'chris',
            'email'=>'christianramos@edu.com.ve',
            'avatar'=>'1808049398.jpg',
            'password'=>bcrypt('123456'),
            'cedula'=>'1',
            'nombres'=>'Christhian',
            'apellidos'=>'Ramos',
            'telefono'=>'0000000',
            'sexo'=>'Masculino',
            'ocupacion'=>'Estudiante',
            'direccion'=>'Universidad de Oriente',
            'created_at'=>'2017-05-21 10:48:05',
            'updated_at'=>'2017-05-21 10:48:05',
        ],[
            'id'=>'10',
            'id_dependencia'=>'2',
            'id_perfil'=>'5',
            'id_pais'=>'1',
            'id_state'=>'1',
            'id_municipio'=>'1',
            'id_ciudad'=>'1',
            'name'=>'nazareth',
            'email'=>'berenicenazareth@edu.com.ve',
            'avatar'=>'1116378371.jpg',
            'password'=>bcrypt('123456'),
            'cedula'=>'1',
            'nombres'=>'Berenice',
            'apellidos'=>'Nazareth',
            'telefono'=>'0000000',
            'sexo'=>'Masculino',
            'ocupacion'=>'Estudiante',
            'direccion'=>'Universidad de Oriente',
            'created_at'=>'2017-05-21 10:48:05',
            'updated_at'=>'2017-05-21 10:48:05',
        ],[
            'id'=>'11',
            'id_dependencia'=>'2',
            'id_perfil'=>'5',
            'id_pais'=>'1',
            'id_state'=>'1',
            'id_municipio'=>'1',
            'id_ciudad'=>'1',
            'name'=>'pj.mabar',
            'email'=>'pj.marbar@edu.com.ve',
            'avatar'=>'foto3.jpg',
            'password'=>bcrypt('123456'),
            'cedula'=>'1',
            'nombres'=>'Pamela',
            'apellidos'=>'Marin',
            'telefono'=>'0000000',
            'sexo'=>'Masculino',
            'ocupacion'=>'Estudiante',
            'direccion'=>'Universidad de Oriente',
            'created_at'=>'2017-05-21 10:48:05',
            'updated_at'=>'2017-05-21 10:48:05',
        ],[
            'id'=>'12',
            'id_dependencia'=>'2',
            'id_perfil'=>'5',
            'id_pais'=>'1',
            'id_state'=>'1',
            'id_municipio'=>'1',
            'id_ciudad'=>'1',
            'name'=>'ana',
            'email'=>'ana@edu.com.ve',
            'avatar'=>'1808049398.jpg',
            'password'=>bcrypt('123456'),
            'cedula'=>'1',
            'nombres'=>'Ana',
            'apellidos'=>'Ramos',
            'telefono'=>'0000000',
            'sexo'=>'Masculino',
            'ocupacion'=>'Estudiante',
            'direccion'=>'Universidad de Oriente',
            'created_at'=>'2017-05-21 10:48:05',
            'updated_at'=>'2017-05-21 10:48:05',
        ],[
            'id'=>'13',
            'id_dependencia'=>'6',
            'id_perfil'=>'6',
            'id_pais'=>'1',
            'id_state'=>'1',
            'id_municipio'=>'1',
            'id_ciudad'=>'1',
            'name'=>'wvelasq',
            'email'=>'wvelasq@edu.com.ve',
            'avatar'=>'1808049398.jpg',
            'password'=>bcrypt('123456'),
            'cedula'=>'1',
            'nombres'=>'Williams',
            'apellidos'=>'Velasquez',
            'telefono'=>'0000000',
            'sexo'=>'Masculino',
            'ocupacion'=>'Director',
            'direccion'=>'Universidad de Oriente',
            'created_at'=>'2017-05-21 10:48:05',
            'updated_at'=>'2017-05-21 10:48:05',
        ],[
            'id'=>'13',
            'id_dependencia'=>'14',
            'id_perfil'=>'2',
            'id_pais'=>'1',
            'id_state'=>'1',
            'id_municipio'=>'1',
            'id_ciudad'=>'1',
            'name'=>'neyla',
            'email'=>'neylacortez@edu.com.ve',
            'avatar'=>'1808049398.jpg',
            'password'=>bcrypt('123456'),
            'cedula'=>'1',
            'nombres'=>'NEYLA',
            'apellidos'=>'CORTEZ',
            'telefono'=>'0000000',
            'sexo'=>'Masculino',
            'ocupacion'=>'Director',
            'direccion'=>'Universidad de Oriente',
            'created_at'=>'2017-05-21 10:48:05',
            'updated_at'=>'2017-05-21 10:48:05',
        ]];
         foreach($User as $Usuarios){
            if(!User::find($Usuarios['id'])){
                DB::table('users')->insert($Usuarios);
            }
        } 
}}
